In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

# STATISTICAL TESTS-ASSIGNMENT

## 1. A physician is evaluating a new diet for her patients with a family history of heart disease. To test the effectiveness of this diet, 16 patients are placed on the diet for 6 months. Their weights and triglyceride levels are measured before and after the study, and the physician wants to know if either set of measurements has changed. (Data set: dietstudy.csv)

2 Sample T-Test(Paired)

In [2]:
diet = pd.read_csv("dietstudy.csv")

In [3]:
diet.head()

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [48]:
print diet.tg0.mean()
print diet.tg4.mean()

138.4375
124.375


In [49]:
print diet.wgt0.mean()
print diet.wgt4.mean()

198.375
190.3125


In [50]:
stats.ttest_rel( a = diet.tg0,
               b = diet.tg4 )

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [53]:
stats.ttest_rel( a = diet.wgt0,
               b = diet.wgt4 )

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

### The weight measurement has significangtly changed with 90% confidence with mean of weight after the study is less than mean of weight before the study but The triglyceride measurement has not significangtly changed with 90% confidence

## 2. An analyst at a department store wants to evaluate a recent credit card promotion. To this end, 500 cardholders were randomly selected. Half received an ad promoting a reduced interest rate on purchases made over the next three months, and half received a standard seasonal ad. Is the promotion effective to increase sales? (Data set: creditpromo.csv)

2 Sample t-test(Independent)

In [32]:
credit = pd.read_csv("creditpromo.csv")

In [33]:
credit.head()

id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

In [36]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
id         500 non-null int64
insert     500 non-null object
dollars    500 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 11.8+ KB


In [40]:
standard = credit.dollars[credit['insert'] == 'Standard']


In [41]:
promo = credit.dollars[credit['insert'] == 'New Promotion']

In [42]:
print standard.head()
print promo.head()

0    2232.771979
2    2327.092181
3    1280.030541
7    1476.624884
8    1460.769753
Name: dollars, dtype: float64
1    1403.807542
4    1513.563200
5    1729.627996
6    1609.705918
9    1854.489028
Name: dollars, dtype: float64


In [45]:
print standard.mean()
print promo.mean()

1566.38903097
1637.49998306


In [46]:
print standard.std()
print promo.std()

346.673047074
356.703168688


In [47]:
stats.ttest_ind(a =standard,
               b = promo, 
               equal_var = False)

Ttest_indResult(statistic=-2.260422726464996, pvalue=0.024226348191648994)

### The promotion is effective to increase sales with 90% confidence with mean of promotion > mean of standard ad

## 3. An experiment is conducted to study the hybrid seed production of bottle gourd under open field conditions. The main aim of the investigation is to compare natural pollination and hand pollination. The data are collected on 10 randomly selected plants from each of natural pollination and hand pollination. The data are collected on fruit weight (kg), seed yield/plant (g) and seedling length (cm). (Data set: pollination.csv)

a. Is the overall population of Seed yield/plant (g) equals to 200?

b. Test whether the natural pollination and hand pollination under open field conditions are equally effective or are significantly different.

In [79]:
pollination = pd.read_csv("pollination.csv")

In [80]:
pollination.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [82]:
print pollination.Seed_Yield_Plant.mean()
print pollination.Seed_Yield_Plant.std()

180.8035
37.3110111128


In [83]:
stats.ttest_1samp(pollination.Seed_Yield_Plant,
           popmean= 200)

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

### with 90% confidence the overall population of Seed yield/plant (g) < 200

## 4. An electronics firm is developing a new DVD player in response to customer requests. Using a prototype, the marketing team has collected focus data for different age groups viz. Under 25; 25-34; 35-44; 45-54; 55-64; 65 and above. Do you think that consumers of various ages rated the design differently? (Data set: dvdplayer.csv).

In [54]:
dvd = pd.read_csv("dvdplayer.csv")

In [61]:
dvd.head()

agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

In [60]:
dvd['agegroup'].value_counts()

65 and over    17
Under 25       13
35-44          12
45-54          10
25-34          10
55-64           6
Name: agegroup, dtype: int64

In [63]:
g1 = dvd.dvdscore[dvd['agegroup']=='Under 25']
g2 = dvd.dvdscore[dvd['agegroup']=='25-34']
g3 = dvd.dvdscore[dvd['agegroup']=='35-44']
g4 = dvd.dvdscore[dvd['agegroup']=='45-54']
g5 = dvd.dvdscore[dvd['agegroup']=='55-64']
g6 = dvd.dvdscore[dvd['agegroup']=='65 and over']

In [64]:
stats.f_oneway(g1,g2,g3,g4,g5,g6)

F_onewayResult(statistic=6.992526962676518, pvalue=3.087324905679639e-05)

In [66]:
print dvd.dvdscore.mean()
print dvd.dvdscore.std()

31.9507635494
7.31999223969


In [65]:
print g1.mean(); print g2.mean(); print g3.mean(); print g4.mean(); print g5.mean(); print g6.mean()

28.7492284256
31.6780099423
37.018058228
39.1183687319
28.4473356921
28.0027913055


### The consumers of different ages have rated the design differently with 98% confidence, age group '45-54' has rated highest and and under 25 has rated lowest 

## 5. A survey was conducted among 2800 customers on several demographic characteristics. Working status, sex, age, age-group, race, happiness, no. of child, marital status, educational qualifications, income group etc. had been captured for that purpose. (Data set: sample_survey.csv).

a. Is there any relationship in between labour force status with marital status?

b. Do you think educational qualification is somehow controlling the marital status?

c. Is happiness is driven by earnings or marital status?

In [68]:
survery = pd.read_csv("sample_survey.csv")

In [69]:
t=pd.crosstab(survery.wrkstat, survery.marital, margins = True)
t

marital                  Divorced  Married  Never married  Separated  Widowed  \
wrkstat                                                                         
Keeping house                  25      200             35         13       55   
Other                          12       16             14          4        8   
Retired                        53      168             17          6      150   
School                          7        9             60          2        1   
Temporarily not working         9       23             11          1        2   
Unemployed, laid off           10       13             32          0        3   
Working full time             295      778            392         58       44   
Working part-time              35      138            102          9       20   
All                           446     1345            663         93      283   

marital                   All  
wrkstat                        
Keeping house             328  
Other                      54  
Retired                   394  
School                     79  
Temporarily not working    46  
Unemployed, laid off       58  
Working full time        1567  
Working part-time         304  
All                      2830

In [70]:
stats.chi2_contingency(observed= t)

(729.2421426572284,
 1.820339965538765e-127,
 40L,
 array([[5.16918728e+01, 1.55886926e+02, 7.68424028e+01, 1.07787986e+01,
         3.28000000e+01, 3.28000000e+02],
        [8.51024735e+00, 2.56643110e+01, 1.26508834e+01, 1.77455830e+00,
         5.40000000e+00, 5.40000000e+01],
        [6.20932862e+01, 1.87254417e+02, 9.23045936e+01, 1.29477032e+01,
         3.94000000e+01, 3.94000000e+02],
        [1.24501767e+01, 3.75459364e+01, 1.85077739e+01, 2.59611307e+00,
         7.90000000e+00, 7.90000000e+01],
        [7.24946996e+00, 2.18621908e+01, 1.07766784e+01, 1.51166078e+00,
         4.60000000e+00, 4.60000000e+01],
        [9.14063604e+00, 2.75653710e+01, 1.35879859e+01, 1.90600707e+00,
         5.80000000e+00, 5.80000000e+01],
        [2.46954770e+02, 7.44740283e+02, 3.67109894e+02, 5.14950530e+01,
         1.56700000e+02, 1.56700000e+03],
        [4.79095406e+01, 1.44480565e+02, 7.12197880e+01, 9.99010601e+00,
         3.04000000e+01, 3.04000000e+02],
        [4.46000000e+02, 1.34

In [71]:
u =pd.crosstab(survery.degree, survery.marital, margins = True)
u

marital         Divorced  Married  Never married  Separated  Widowed   All
degree                                                                    
Bachelor              58      251            129         12       28   478
Graduate              29      123             41          3        9   205
High school          241      686            367         58      148  1500
Junior college        45      108             46          3        6   208
LT High school        70      174             77         17       92   430
All                  443     1342            660         93      283  2821

In [74]:
stats.chi2_contingency(observed= u)

(122.68449020508541,
 7.424404099753273e-15,
 25L,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [75]:
v =pd.crosstab(survery.happy, survery.marital, margins = True)
v

marital        Divorced  Married  Never married  Separated  Widowed   All
happy                                                                    
Not too happy        72       71            108         30       59   340
Pretty happy        278      684            426         49      137  1574
Very happy           93      582            120         13       83   891
All                 443     1337            654         92      279  2805

In [76]:
stats.chi2_contingency(observed= v)

(260.68943894182826,
 7.762777322980048e-47,
 15L,
 array([[  53.6969697 ,  162.06060606,   79.27272727,   11.15151515,
           33.81818182,  340.        ],
        [ 248.58538324,  750.24527629,  366.98609626,   51.62495544,
          156.55828877, 1574.        ],
        [ 140.71764706,  424.69411765,  207.74117647,   29.22352941,
           88.62352941,  891.        ],
        [ 443.        , 1337.        ,  654.        ,   92.        ,
          279.        , 2805.        ]]))

In [77]:
w =pd.crosstab(survery.happy, survery.income, margins = True)
w

income         $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
happy                                                                          
Not too happy              7              39              33              40   
Pretty happy              20             107             119             155   
Very happy                 5              44              26              50   
All                       32             190             178             245   

income         $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
happy                                                                        
Not too happy             113              9              9              6   
Pretty happy              888             11             13             18   
Very happy                571              4             10             11   
All                      1572             24             32             35   

income         $6000 TO 6999  $7000 TO 7999  $8000 TO 9999  LT $1000   All  
happy                                                                       
Not too happy             14             12              9        11   302  
Pretty happy              13             21             30        13  1408  
Very happy                 6             14             19        11   771  
All                       33             47             58        35  2481

In [78]:
stats.chi2_contingency(observed= w)

(178.95053061216427,
 7.234749067043371e-21,
 36L,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))